baseURL = 'https://itsleg.day'
languageCode = 'en-us'
title = "It's Leg Day"

[params.homeInfoParams]
Title = "It's Leg Day: A sporadic collection of unrelated topics"
Content = "My personal blog for fleshing out ideas and long-form information. All opinions are my own."

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
